SELECT id,
       bill_id,
       recipe_code,
       department_name,
       pick_up_no,
       hospital_code,
       hospital_name,
       health_card_no,
       patient_name,
       prescription_time,
       remark,
       commit,
       auto_fill,
       recipient_tel,
       customer_id,
       delivery_type,
       delivery_status,
       state_id,
       qr_code,
       qr_code_sign_for,
       add_ice_bag,
       is_push_delivery,
       create_time,
       update_time,
       pick_up_tel,
       belong,
       arrived_hospital_time,
       recipient_code,
       reminded_pick_up,
       commit_time,
       decoction_money,
       pay_status,
       total_package_paste,
       boil_type,
       carry_type
FROM prescription_info
WHERE (customer_id = '1673884108486930566' AND commit = true) and recipe_code='20250429017';